_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 53
                - 55
                - 71
                - 80
                - 98
                - 105
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 53
                - 55
                - 71
                - 80
                - 98
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.12
            "5": 0.19.9
            "6": 4.51.3
            "8":
                - 1
                - 5
                - 12
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 4
classes:
    value:
        - Human
        - Car
        - Truck
        - Van
        - Motorbike
        - Bicycle
        - Bus
        - Trailer
early_stopping_patience:
    value: 4
effective_batch_size:
    value: 64
epochs:
    value: 20
grad_accumulation_steps:
    value: 16
learning_rate:
    value: 3e-05
model_checkpoint:
    value: hustvl/yolos-small
num_classes:
    value: 8
warmup_ratio:
    value: 0.05
